# Generated by Django 3.0 on 2019-12-03 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palestra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('palestrante', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=1000)),
                ('sala', models.CharField(max_length=20)),
                ('data', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Form_Satisfacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('palestrante', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=1000)),
                ('sala', models.CharField(max_length=20)),
                ('data', models.DateTimeField()),
                ('id_palestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Palestra')),
            ],
        ),
    ]
