# Generated by Django 3.0 on 2019-12-17 15:51

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('nome', models.CharField(blank=True, max_length=30, verbose_name='nome')),
                ('dre', models.CharField(blank=True, max_length=9, verbose_name='dre')),
                ('is_staff', models.BooleanField(blank=True, default=False, verbose_name='Eh da equipe?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', api.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Palestra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=100)),
                ('palestrante', models.CharField(max_length=100)),
                ('descricao_palestra', models.CharField(max_length=1000)),
                ('descricao_palestrante', models.CharField(max_length=1000)),
                ('sala', models.CharField(max_length=20)),
                ('horario', models.CharField(max_length=20)),
                ('data', models.CharField(max_length=15)),
                ('favorito', models.ManyToManyField(blank=True, related_name='favorito', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pergunta1', models.CharField(max_length=100)),
                ('Pergunta2', models.CharField(max_length=100)),
                ('Pergunta3', models.CharField(max_length=100)),
                ('Pergunta4', models.CharField(max_length=100)),
                ('Pergunta5', models.CharField(max_length=100)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_palestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Palestra')),
            ],
        ),
    ]
