# Generated by Django 3.0 on 2020-01-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='palestra',
            name='foto_palestrante',
            field=models.ImageField(blank=True, null=True, upload_to='fotos'),
        ),
    ]
