# Generated by Django 3.0.3 on 2020-02-07 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='palestra',
            name='foi_na_palestra',
            field=models.ManyToManyField(blank=True, related_name='foi_na_palestra', to=settings.AUTH_USER_MODEL),
        ),
    ]
