# Generated by Django 3.0.3 on 2020-02-07 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_palestra_foi_na_palestra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='form',
            name='id_palestra',
        ),
    ]
