# Generated by Django 3.0.3 on 2020-02-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_form_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='nome'),
        ),
    ]
