# Generated by Django 3.0.3 on 2020-02-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_form_palestra_pertencente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palestra',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='IntegerFieldemail address'),
        ),
    ]
