# Generated by Django 3.0.3 on 2020-02-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200213_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palestra',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='palestra',
            name='horario',
            field=models.TimeField(),
        ),
    ]
