# Generated by Django 3.0.3 on 2020-02-17 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_form_palestra_pertencente'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='pa_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Palestra'),
            preserve_default=False,
        ),
    ]
