# Generated by Django 3.0.3 on 2020-02-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_form_pa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palestra',
            name='data',
            field=models.CharField(max_length=10),
        ),
    ]
