# Generated by Django 3.0.3 on 2020-02-29 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200218_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='foto_perfil',
        ),
    ]
