# Generated by Django 3.0.3 on 2020-03-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_user_foto_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='palestra',
            old_name='descricao_palestra',
            new_name='descricaopalestra',
        ),
        migrations.RenameField(
            model_name='palestra',
            old_name='descricao_palestrante',
            new_name='descricaopalestrante',
        ),
        migrations.RenameField(
            model_name='palestra',
            old_name='data',
            new_name='dia',
        ),
        migrations.RenameField(
            model_name='palestra',
            old_name='foto_palestrante',
            new_name='fotopalestrante',
        ),
        migrations.RenameField(
            model_name='palestra',
            old_name='horario',
            new_name='inicio',
        ),
        migrations.AddField(
            model_name='palestra',
            name='termino',
            field=models.TimeField(default='12:00:00'),
            preserve_default=False,
        ),
    ]
