# Generated by Django 3.0.4 on 2020-03-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200302_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palestra',
            name='tema',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
