# Generated by Django 3.0.4 on 2020-03-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_parceiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primaria', models.CharField(max_length=7)),
                ('secundaria', models.CharField(max_length=7)),
                ('terciaria', models.CharField(max_length=7)),
            ],
        ),
    ]
