# Generated by Django 3.0.4 on 2020-03-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_cores'),
    ]

    operations = [
        migrations.AddField(
            model_name='cores',
            name='quaternaria',
            field=models.CharField(default='#ffffff', max_length=7),
            preserve_default=False,
        ),
    ]
