# Generated by Django 3.0.4 on 2020-04-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_cores_quaternaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cores',
            name='texto',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
