# Generated by Django 3.0.4 on 2020-04-10 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_cores_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pri', models.CharField(max_length=7)),
                ('seg', models.CharField(max_length=7)),
                ('ter', models.CharField(max_length=7)),
                ('qua', models.CharField(max_length=7)),
                ('qui', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
    ]
