# Generated by Django 3.0.4 on 2020-04-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200410_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='cores',
            name='dark_terciaria',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.DeleteModel(
            name='Form',
        ),
    ]
